#Para poder usar este archivo de propiedades, es necesario crear
#la clase AppConfig.java en el paquete principal de la aplicación.
client.name=Yorking
client.lastname=Máster
invoice.description=Invoice sports
invoice.description.office=Invoice office supplies